export const Task = [
    {
        id: 1,
        title: "The beginning of the task",
        description: "Always try your best to do what you need to do for the day. Do no give in to procrastination.Always try your best to do what you need to do for the day. Do no give in to procrastination.Always try your best to do what you need to do for the day. Do no give in to procrastination.Always try your best to do what you need to do for the day. Do no give in to procrastination.Always try your best to do what you need to do for the day. Do no give in to procrastination.Always try your best to do what you need to do for the day. Do no give in to procrastination.I don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timevI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right time",
        dueDate: "10/02/2024",
        status: "Ongoing",
    },
    {
        id: 2,
        title: "Some days are good",
        description: "I don't know how it gonna be, but God will do it at the right time.Always try your best to do what you need to do for the day. Do no give in to procrastination.Always try your best to do what you need to do for the day. Do no give in to procrastination.Always try your best to do what you need to do for the day. Do no give in to procrastination.",
        dueDate: "07/02/2024",
        status: "Completed",
    },
    {
        id: 3,
        title: "Perfect your skills on Api",
        description: "Read on the best practices for Api implementation",
        dueDate: "17/02/2024",
        status: "Pending",
    },
    {
        id: 4,
        title: "API Integration",
        description: "Read on the best practices for API Integrations and NextJs Routing.Always try your best to do what you need to do for the day. Do no give in to procrastination.Always try your best to do what you need to do for the day. Do no give in to procrastination.Always try your best to do what you need to do for the day. Do no give in to procrastination.",
        dueDate: "23/02/2024",
        status: "Ongoing",
    },
    {
        id: 5,
        title: "Some days are good",
        description: "I don't know how it gonna be, but God will do it at the right time.I don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right time.I don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timeI don't know how it gonna be, but God will do it at the right timevvI don't know how it gonna be, but God will do it at the right time",
        dueDate: "07/02/2024",
        status: "Completed",
    },
    {
        id: 6,
        title: "The beginning of the task",
        description: "Always try your best to do what you need to do for the day. Do no give in to procrastination.",
        dueDate: "10/02/2024",
        status: "Ongoing",
    },
    {
        id: 7,
        title: "API Integration",
        description: "Read on the best practices for API Integrations and NextJs Routing",
        dueDate: "23/02/2024",
        status: "Ongoing",
    },
]